/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToastHost: typeof import('./src/components/ui/AppToastHost.vue')['default']
    AuthUsersTab: typeof import('./src/components/config/AuthUsersTab.vue')['default']
    BarChart: typeof import('./src/components/charts/BarChart.vue')['default']
    ClaudeCliConfigTab: typeof import('./src/components/config/ClaudeCliConfigTab.vue')['default']
    ConfigActionBar: typeof import('./src/components/config/ConfigActionBar.vue')['default']
    ConfigSectionHeader: typeof import('./src/components/config/ConfigSectionHeader.vue')['default']
    EventPromptTab: typeof import('./src/components/project/EventPromptTab.vue')['default']
    GitLabConfigTab: typeof import('./src/components/config/GitLabConfigTab.vue')['default']
    IconButton: typeof import('./src/components/ui/IconButton.vue')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    LLMProviderTab: typeof import('./src/components/config/LLMProviderTab.vue')['default']
    NotificationChannelsTab: typeof import('./src/components/config/NotificationChannelsTab.vue')['default']
    NotificationTab: typeof import('./src/components/project/NotificationTab.vue')['default']
    PieChart: typeof import('./src/components/charts/PieChart.vue')['default']
    ProjectInfoTab: typeof import('./src/components/project/ProjectInfoTab.vue')['default']
    ProjectSidebar: typeof import('./src/components/project/ProjectSidebar.vue')['default']
    PublicReportShell: typeof import('./src/components/reports/PublicReportShell.vue')['default']
    RecentEventsTab: typeof import('./src/components/project/RecentEventsTab.vue')['default']
    ReviewSnippetConfigTab: typeof import('./src/components/config/ReviewSnippetConfigTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarContent: typeof import('./src/components/SidebarContent.vue')['default']
    SimpleModal: typeof import('./src/components/ui/SimpleModal.vue')['default']
    WebhookEventRulesTab: typeof import('./src/components/config/WebhookEventRulesTab.vue')['default']
    WebhookEventTab: typeof import('./src/components/project/WebhookEventTab.vue')['default']
    WeeklySnapshotSchedulerConfigTab: typeof import('./src/components/config/WeeklySnapshotSchedulerConfigTab.vue')['default']
  }
}
